### ISSUE TITLE
[1.12.2] Issue with sending packages to minus Z coordinates

### ISSUE THREAD

**Issue by fkrisi11** [MattCzyr/EnderMail#2]
Hey there,

I noticed something after installing the mod and investigating further into this issue I was having.
Now I see that you can send packages to minus coordinates, by filling out all 3 coordinate textboxes.

If you leave any of the text fields empty, you can't write minus symbols.
This only seems to apply to the Z coordinate textbox however.

**Comment by fkrisi11** [comment]
Oh I see now.. it doesn't work with the numpad minus symbol.
Using a Hungarian QWERTZ layout keyboard.
I could use the - symbol that is next to right shift though.

Don't know if this is a possible enhancement that you guys can add, or if this is just something silly on my part

**Comment by MattCzyr** [comment]
Just tested it myself and it looks like, for some reason, you can only insert a minus symbol if all the previous text fields contain text. So, as long as you insert a Y coordinate you'll be able to insert a negative Z coordinate. I recommend using this as a workaround until this is fixed in the next release.

**Comment by fkrisi11** [comment]
Alright. I will do that then

**Comment by MattCzyr** [comment]
Fixed in version 1.12.2-1.0.1.
