### ISSUE TITLE
Undelivered mail vanished?

### ISSUE THREAD

**Issue by istoOi** [MattCzyr/EnderMail#38]
Hi,

i'm playing on a 1.16.3 server with endermail 1.1.5

We have sent two packages to non-existing locker IDs and one from the nether to a locker in the overworld.

Where should this packages be? They're not at spawn nor were returned to sender.

**Comment by MattCzyr** [comment]
This issue was fixed in version 1.2.0, see #30 for more info. The lost packages should be at coordinates -1, -1 in the dimension they were sent in, likely at the highest point with solid ground underneath. That means the package sent in the nether is probably on top of the bedrock roof at -1, -1, and the overworld packages should be on the ground at -1, -1 in the overworld.
