### ISSUE TITLE
[1.12.2] Empty package

### ISSUE THREAD

**Issue by fkrisi11** [MattCzyr/EnderMail#5]
I sent a package today on my server, and everything was fine. The delivery was successful, but the package was empty.

How can this happen?

**Comment by MattCzyr** [comment]
Does this occur every time you send a package, or just this isolated incident?

**Comment by fkrisi11** [comment]
This happened 1 time out of the total 2 so far

**Comment by MattCzyr** [comment]
I haven't been able to reproduce this issue so far. If it happens again, let me know what conditions I may be able to reproduce it under.

**Comment by fkrisi11** [comment]
Thanks for investigating. I will definitely let you know if I found something

**Comment by MattCzyr** [comment]
I believe this issue is related to a bug that was just fixed in version 1.0.3 for 1.12.2. In this bug, stamped packages would appear unstamped on servers, and right-clicking them would open an empty package inventory. I'm closing this issue for now, but let me know if it turns out to not be resolved.

**Comment by fkrisi11** [comment]
I see.
Thank you for the update ^^
